### ISSUE TITLE
GCP stack example uses AWS provider, resources

### ISSUE THREAD

**Issue by AndrewADev** [terrarium-tf/cli#3]
Currently, the `main.tf` of the GCP stack example starts by [defining an AWS provider](https://github.com/terrarium-tf/cli/blob/main/example/stack_gcp/main.tf#L1):
```terraform
provider "aws" {
  region = "eu-central-1"
}
```

Later defining some [AWS-specific resources](https://github.com/terrarium-tf/cli/blob/main/example/stack_gcp/main.tf#L16):
```terraform
resource "aws_s3_bucket" "test" {
  bucket = "test-${var.environment}-${data.aws_caller_identity.self.account_id}"
}

resource "aws_s3_bucket" "state" {}
```

I imagine these should probably be GCP-based as well? (in addition to the [backend](https://github.com/terrarium-tf/cli/blob/main/example/stack_gcp/main.tf#L23)?)

**Comment by digitalkaoz** [comment]
done with 1.3.1 thanks for reporting!
